<?php

namespace AppBundle\Repository;

/**
 * PropertyMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
