<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends EntityRepository
{
    public function getAffIds()
    {
        $result = $this->createQueryBuilder('p')
            ->select('p.affId')
            ->getQuery()
            ->getScalarResult();

       return array_map('current', $result);
    }
}
