<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Property;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends EntityRepository
{
    public function getAffIds()
    {
        $result = $this->createQueryBuilder('p')
            ->select('p.affId')
            ->getQuery()
            ->getScalarResult();

       return array_map('current', $result);
    }

    public function getCarouselProperties()
    {
        $query = $this->createQueryBuilder('p')
            ->join('p.medias', 'm')
            ->addSelect('m.imageUrl')
            ->andWhere('m.cover = true')
            ->andWhere('p.inCarousel = true')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();

        return $query;
    }

    public function getPropertiesPaginated(int $limit, int $page)
    {
        $query = $this->createQueryBuilder('p')
            ->getQuery();

        $pagerfanta = new Pagerfanta(new DoctrineORMAdapter($query));
        $pagerfanta->setMaxPerPage($limit)
            ->setCurrentPage($page)
            ->setAllowOutOfRangePages(true);

        return $pagerfanta;
    }
}
