<?php

namespace AppBundle\Repository;

/**
 * PropertyInsideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyInsideRepository extends \Doctrine\ORM\EntityRepository
{
}
