<?php

namespace AppBundle\Repository;

/**
 * PropertyOtherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyOtherRepository extends \Doctrine\ORM\EntityRepository
{
}
