<?php

namespace AppBundle\Repository;

/**
 * PropertyOutsideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyOutsideRepository extends \Doctrine\ORM\EntityRepository
{
}
